// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5PQS6JGc9V0jkxrSLA8w2j55e3KvyNT8',
    appId: '1:433942891421:web:ae7b37ec2d513dc0f4fd74',
    messagingSenderId: '433942891421',
    projectId: 'my-chat-315c8',
    authDomain: 'my-chat-315c8.firebaseapp.com',
    storageBucket: 'my-chat-315c8.appspot.com',
    measurementId: 'G-YJGRNCFDCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpe4CGU2735a6l7bIF1O-9IFIrmLkB-1M',
    appId: '1:433942891421:android:f8f9c75c99975c49f4fd74',
    messagingSenderId: '433942891421',
    projectId: 'my-chat-315c8',
    storageBucket: 'my-chat-315c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_kLr3JWWTAzKLn26TTzr8a4rcux1ZwXo',
    appId: '1:433942891421:ios:49cb99adf1b4bf60f4fd74',
    messagingSenderId: '433942891421',
    projectId: 'my-chat-315c8',
    storageBucket: 'my-chat-315c8.appspot.com',
    iosBundleId: 'com.example.myChatApp',
  );
}
